import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/Navbar/page";

export const metadata: Metadata = {
  title: "LibroHub",
  description: "Generated by create next app",
};
const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
