import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/Navbar/page";
import Footer from "@/_components/Footer/page";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/_components/ReduxProvider/page";

export const metadata: Metadata = {
  title: "LibroHub",
  description: "Generated by create next app",
};
const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
